apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibm-block-custom-ocs
parameters:
  billingType: hourly
  classVersion: "1"
  csi.storage.k8s.io/fstype: ext4
  encrypted: "false"
  encryptionKey: ""
  profile: 10iops-tier
  region: ""
  resourceGroup: ""
  sizeRange: '[10-2000]GiB'
  tags: ""
  zone: ""
provisioner: vpc.block.csi.ibm.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer